### ISSUE TITLE
Create an attractive README for this Score-Keeper repo

### ISSUE THREAD

**Issue by kanchi2438** [kanchi2438/Score-Keeper-Repo#5]
Do add it's preview , tech stack used (HTML 5, CSS, JavaScript) and it's use .
Also star the repo , if you like it :)

**Comment by vijaykrishna536** [comment]
Hi @kanchi2438 Would like to work on this. Do you want anything in particular?

**Comment by kanchi2438** [comment]
@vijaykrishna536 Make a good looking README.md file for this repo . It's a small Score-keeper web app that can help you to manage your scores in a two player game . More details are given above .
Check this out too if needed : [https://kanchi2438.github.io/Score-Keeper-Repo/](url)
There're small bugs (like it also accepts a negative number) , you can ignore it for now .

**Comment by Ayush-Khandelwal-007** [comment]
I can solve the issue for negative input.
Please create a issue and assign me.

**Comment by kanchi2438** [comment]
Hey @Ayush-Khandelwal-007 !! I've opened the issue , you can check it out now

**Comment by kanchi2438** [comment]
@Ayush-Khandelwal-007 issue is resolved now
